project:
  title: "R Beats Python"
  type: website

website:
  title: "R Beats Python"
  favicon: favicon.ico
  description: "Exploring where R excels over Python in data science and statistics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog/
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    number-sections: true
    code-fold: true
    code-tools: true
    fig-cap-location: bottom
    link-external-newwindow: true
    html-math-method: katex
    lang: en


execute:
  echo: true
  eval: true  # Set to false to avoid package dependency issues
  warning: false
  error: false